"""
TrafficEye – PDF e-challan generation (ReportLab).

generate_challan(record) builds reports/challan_<id>.pdf containing:
  * TrafficEye header with logo, challan ID, issue date/time
  * violation type, offence, legal reference, vehicle number,
    detection confidence, source file and fine amount
  * the annotated evidence image
  * a clear "Auto-generated by TrafficEye (demo prototype)" note

The ₹ sign needs a font that contains it. DejaVu Sans ships with matplotlib
(installed by Ultralytics), so it is found automatically; system DejaVu or Arial
fonts are tried next. If none is available the challan falls back to "Rs.".
"""
from __future__ import annotations

import importlib.util
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Image, KeepTogether, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from backend import config
from backend.database import resolve_stored_path, stored_path

logger = logging.getLogger("trafficeye.report")

RUPEE = "\u20b9"
PAGE_WIDTH, PAGE_HEIGHT = A4
MARGIN = 18 * mm
CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN
EVIDENCE_MAX_HEIGHT = 95 * mm

# Brand colours (match the web UI)
INK = colors.HexColor("#0f172a")
MUTED = colors.HexColor("#64748b")
RED = colors.HexColor("#dc2626")
AMBER = colors.HexColor("#f59e0b")
LIGHT = colors.HexColor("#f8fafc")
BORDER = colors.HexColor("#e2e8f0")


class ReportError(RuntimeError):
    """The PDF could not be generated."""


# ---------------------------------------------------------------------------
# Fonts
# ---------------------------------------------------------------------------
_fonts: tuple[str, str, str] | None = None      # (regular, bold, currency symbol)


def _font_candidates() -> list[tuple[Path, Path]]:
    """(regular, bold) font file pairs to try, most preferred first."""
    candidates = []
    spec = importlib.util.find_spec("matplotlib")
    if spec and spec.submodule_search_locations:
        ttf_dir = Path(list(spec.submodule_search_locations)[0]) / "mpl-data" / "fonts" / "ttf"
        candidates.append((ttf_dir / "DejaVuSans.ttf", ttf_dir / "DejaVuSans-Bold.ttf"))
    for linux_dir in (Path("/usr/share/fonts/truetype/dejavu"), Path("/usr/share/fonts/TTF")):
        candidates.append((linux_dir / "DejaVuSans.ttf", linux_dir / "DejaVuSans-Bold.ttf"))
    windows_fonts = Path(os.environ.get("WINDIR", "C:/Windows")) / "Fonts"
    candidates.append((windows_fonts / "arial.ttf", windows_fonts / "arialbd.ttf"))
    return candidates


def _load_font(name: str, path: Path) -> bool:
    """Register a TTF font if it exists and contains the ₹ glyph."""
    if not path.is_file():
        return False
    try:
        font = TTFont(name, str(path))
        if ord(RUPEE) not in font.face.charToGlyph:
            return False
        pdfmetrics.registerFont(font)
        return True
    except Exception:
        logger.warning("Could not load font %s", path, exc_info=True)
        return False


def get_fonts() -> tuple[str, str, str]:
    """Register the challan fonts once and return (regular, bold, currency symbol)."""
    global _fonts
    if _fonts is not None:
        return _fonts
    for regular, bold in _font_candidates():
        if _load_font("TE-Regular", regular):
            bold_name = "TE-Bold" if _load_font("TE-Bold", bold) else "TE-Regular"
            logger.info("Challan font: %s", regular)
            _fonts = ("TE-Regular", bold_name, RUPEE)
            return _fonts
    logger.warning("No font with the rupee sign found - challans will use 'Rs.'")
    _fonts = ("Helvetica", "Helvetica-Bold", "Rs.")
    return _fonts


def format_amount(amount: int, symbol: str) -> str:
    """Indian digit grouping: 1000 -> ₹1,000 ; 150000 -> ₹1,50,000."""
    digits = str(int(amount))
    if len(digits) > 3:
        head, tail = digits[:-3], digits[-3:]
        groups = []
        while len(head) > 2:
            groups.insert(0, head[-2:])
            head = head[:-2]
        if head:
            groups.insert(0, head)
        digits = ",".join(groups + [tail])
    return f"{symbol}{digits}" if symbol == RUPEE else f"{symbol} {digits}"


# ---------------------------------------------------------------------------
# Page decoration (header band, logo, footer)
# ---------------------------------------------------------------------------
def _draw_logo(canvas: Any, x: float, y: float) -> None:
    """Simple eye mark: amber outline with a red pupil."""
    canvas.setStrokeColor(AMBER)
    canvas.setLineWidth(1.6)
    canvas.ellipse(x, y, x + 12 * mm, y + 7 * mm, stroke=1, fill=0)
    canvas.setFillColor(RED)
    canvas.circle(x + 6 * mm, y + 3.5 * mm, 2 * mm, stroke=0, fill=1)


def _page_decorator(generated_at: datetime):
    regular, bold, _ = get_fonts()

    def draw(canvas: Any, doc: Any) -> None:
        canvas.saveState()

        # Dark header band + red/amber accent line
        band_height = 30 * mm
        canvas.setFillColor(INK)
        canvas.rect(0, PAGE_HEIGHT - band_height, PAGE_WIDTH, band_height, stroke=0, fill=1)
        canvas.setFillColor(RED)
        canvas.rect(0, PAGE_HEIGHT - band_height - 1.5 * mm, PAGE_WIDTH / 2, 1.5 * mm, stroke=0, fill=1)
        canvas.setFillColor(AMBER)
        canvas.rect(PAGE_WIDTH / 2, PAGE_HEIGHT - band_height - 1.5 * mm, PAGE_WIDTH / 2, 1.5 * mm, stroke=0, fill=1)

        _draw_logo(canvas, MARGIN, PAGE_HEIGHT - 19 * mm)
        canvas.setFillColor(colors.white)
        canvas.setFont(bold, 20)
        canvas.drawString(MARGIN + 15 * mm, PAGE_HEIGHT - 17 * mm, "TrafficEye")
        canvas.setFillColor(colors.HexColor("#cbd5e1"))
        canvas.setFont(regular, 8.5)
        canvas.drawString(MARGIN + 15 * mm, PAGE_HEIGHT - 22.5 * mm, "Intelligent Traffic Violation Detection")

        canvas.setFillColor(AMBER)
        canvas.setFont(bold, 18)
        canvas.drawRightString(PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 16 * mm, "E-CHALLAN")
        canvas.setFillColor(colors.HexColor("#cbd5e1"))
        canvas.setFont(regular, 8.5)
        canvas.drawRightString(PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 22.5 * mm, "Traffic Violation Notice")

        # Footer
        canvas.setStrokeColor(BORDER)
        canvas.setLineWidth(0.6)
        canvas.line(MARGIN, 16 * mm, PAGE_WIDTH - MARGIN, 16 * mm)
        canvas.setFillColor(MUTED)
        canvas.setFont(regular, 7.5)
        canvas.drawString(MARGIN, 11 * mm, "Auto-generated by TrafficEye (demo prototype). Not a legally valid challan.")
        canvas.drawRightString(
            PAGE_WIDTH - MARGIN, 11 * mm,
            f"Generated {generated_at:%d %b %Y, %H:%M:%S}  ·  Page {doc.page}",
        )
        canvas.restoreState()

    return draw


# ---------------------------------------------------------------------------
# Challan body
# ---------------------------------------------------------------------------
def _styles() -> dict[str, ParagraphStyle]:
    regular, bold, _ = get_fonts()
    return {
        "label": ParagraphStyle("label", fontName=bold, fontSize=7.5, leading=10, textColor=MUTED),
        "big": ParagraphStyle("big", fontName=bold, fontSize=15, leading=19, textColor=INK),
        "fine": ParagraphStyle("fine", fontName=bold, fontSize=22, leading=26, textColor=RED),
        "small": ParagraphStyle("small", fontName=regular, fontSize=8, leading=11, textColor=MUTED),
        "heading": ParagraphStyle("heading", fontName=bold, fontSize=11, leading=14, textColor=INK, spaceAfter=2 * mm),
        "cell_label": ParagraphStyle("cell_label", fontName=bold, fontSize=9, leading=12, textColor=MUTED),
        "cell": ParagraphStyle("cell", fontName=regular, fontSize=9.5, leading=12.5, textColor=INK),
        "cell_strong": ParagraphStyle("cell_strong", fontName=bold, fontSize=10.5, leading=13, textColor=INK),
        "caption": ParagraphStyle("caption", fontName=regular, fontSize=7.5, leading=10, textColor=MUTED, spaceBefore=1.5 * mm),
    }


def _summary_block(record: Any, styles: dict[str, ParagraphStyle], currency: str) -> Table:
    """Challan number + issue date on the left, fine amount on the right."""
    left = [
        Paragraph("CHALLAN NO.", styles["label"]),
        Paragraph(escape(record.challan_id), styles["big"]),
        Paragraph(f"Issued {record.created_at:%d %b %Y, %H:%M:%S}", styles["small"]),
    ]
    right = [
        Paragraph("FINE AMOUNT", styles["label"]),
        Paragraph(format_amount(record.fine, currency), styles["fine"]),
        Paragraph("Payable by the registered owner", styles["small"]),
    ]
    table = Table([[left, right]], colWidths=[CONTENT_WIDTH * 0.6, CONTENT_WIDTH * 0.4])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), LIGHT),
                ("BOX", (0, 0), (-1, -1), 0.6, BORDER),
                ("LINEBEFORE", (1, 0), (1, 0), 3, RED),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5 * mm),
                ("TOPPADDING", (0, 0), (-1, -1), 4 * mm),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4 * mm),
            ]
        )
    )
    return table


def _details_table(record: Any, styles: dict[str, ParagraphStyle]) -> Table:
    offence, legal_reference = config.VIOLATION_OFFENCES.get(record.type, ("Traffic rule violation", "—"))
    plate = record.plate_number or config.PLATE_NOT_DETECTED
    if plate == config.PLATE_NOT_DETECTED:
        plate_text = "Not detected (manual verification required)"
    else:
        plate_text = plate

    rows = [
        ("Challan ID", record.challan_id, False),
        ("Date & time of violation", f"{record.created_at:%d %b %Y, %H:%M:%S}", False),
        ("Violation", config.VIOLATION_LABELS.get(record.type, record.type), True),
        ("Offence", offence, False),
        ("Legal reference", legal_reference, False),
        ("Vehicle number", plate_text, True),
        ("Detection confidence", f"{record.confidence * 100:.1f}%", False),
        ("Source file", record.source_file, False),
        ("Detected by", "TrafficEye AI (YOLOv8 detection + EasyOCR plate reading)", False),
    ]
    data = [
        [Paragraph(label, styles["cell_label"]), Paragraph(escape(str(value)), styles["cell_strong" if strong else "cell"])]
        for label, value, strong in rows
    ]
    table = Table(data, colWidths=[CONTENT_WIDTH * 0.32, CONTENT_WIDTH * 0.68])
    table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 0.6, BORDER),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, BORDER),
                ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, LIGHT]),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 3 * mm),
                ("TOPPADDING", (0, 0), (-1, -1), 1.8 * mm),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 1.8 * mm),
            ]
        )
    )
    return table


def _evidence_block(record: Any, styles: dict[str, ParagraphStyle]) -> list[Any]:
    flowables: list[Any] = [Paragraph("Photographic evidence", styles["heading"])]
    evidence_file = resolve_stored_path(record.evidence_path, config.EVIDENCE_DIR)
    if evidence_file is None or not evidence_file.is_file():
        flowables.append(Paragraph("Evidence image not available.", styles["cell"]))
        return flowables
    try:
        img_w, img_h = ImageReader(str(evidence_file)).getSize()
        scale = min(CONTENT_WIDTH / img_w, EVIDENCE_MAX_HEIGHT / img_h)
        flowables.append(Image(str(evidence_file), width=img_w * scale, height=img_h * scale))
        flowables.append(
            Paragraph(
                "Annotated frame captured by TrafficEye. Red boxes mark the violating vehicle and riders; "
                "green boxes mark other road users.",
                styles["caption"],
            )
        )
    except Exception:
        logger.warning("Could not embed evidence image %s", evidence_file, exc_info=True)
        flowables.append(Paragraph("Evidence image could not be embedded.", styles["cell"]))
    return flowables


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------
def challan_path(violation_id: int) -> Path:
    return config.REPORT_DIR / f"challan_{violation_id}.pdf"


def generate_challan(record: Any) -> str:
    """
    Build the PDF for one violation record (any object with the ViolationRecord
    attributes) and return its project-relative path, e.g. "reports/challan_7.pdf".
    """
    _, _, currency = get_fonts()
    styles = _styles()
    output = challan_path(record.id)
    temp_output = output.with_name(f"{output.stem}.tmp.pdf")
    generated_at = datetime.now()

    doc = SimpleDocTemplate(
        str(temp_output),
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=40 * mm,
        bottomMargin=22 * mm,
        title=f"E-Challan {record.challan_id}",
        author="TrafficEye",
        subject=f"{config.VIOLATION_LABELS.get(record.type, record.type)} - {record.plate_number}",
    )
    story = [
        _summary_block(record, styles, currency),
        Spacer(1, 6 * mm),
        Paragraph("Violation details", styles["heading"]),
        _details_table(record, styles),
        Spacer(1, 6 * mm),
        KeepTogether(_evidence_block(record, styles)),
    ]

    try:
        config.REPORT_DIR.mkdir(parents=True, exist_ok=True)
        decorate = _page_decorator(generated_at)
        doc.build(story, onFirstPage=decorate, onLaterPages=decorate)
        temp_output.replace(output)        # only a complete PDF ever gets the final name
    except Exception as exc:
        temp_output.unlink(missing_ok=True)
        logger.exception("Challan generation failed for violation %s", record.id)
        raise ReportError(f"Could not generate challan for violation {record.id}: {exc}") from exc

    logger.info("Generated %s", output.name)
    return stored_path("reports", output.name)
